### register
POST {{gophermart_host}}/api/user/register
Content-Type: application/json

{
  "login": "<login>",
  "password": "<password>"
}

### login
POST {{gophermart_host}}/api/user/login
Content-Type: application/json

{
"login": "<login>",
"password": "<password>"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

### create orders
POST {{gophermart_host}}/api/user/orders HTTP/1.1
Authorization: {{auth_token}}
Content-Type: text/plain

12345678903
### get orders
GET {{gophermart_host}}/api/user/orders HTTP/1.1
Authorization: {{auth_token}}


### get balance
GET {{gophermart_host}}/api/user/balance HTTP/1.1
Authorization: {{auth_token}}


### withdraw balance
POST {{gophermart_host}}/api/user/balance/withdraw HTTP/1.1
Authorization: {{auth_token}}
Content-Type: application/json

{
    "order": "2377225624",
    "sum": 751
}

### get withdrawals
GET {{gophermart_host}}/api/user/withdrawals HTTP/1.1
Authorization: {{auth_token}}


### get accrual order
GET {{accrual_host}}/api/orders/{number} HTTP/1.1
Authorization: {{auth_token}}

